### ISSUE TITLE
Extract sources directory into a separate repository

### ISSUE THREAD

**Issue by dwillis** [NYTimes/Fech#74]
So that new formats could be updated separately and could be included as a submodule in both Fech and software in other languages.

**Comment by saizai** [comment]
Note #75.

**Comment by dwillis** [comment]
New repo here: https://github.com/dwillis/fech-sources

Working on including as submodule.

**Comment by bycoffe** [comment]
This is great. I will take a closer look but definitely think this is the right direction, since the sources are such an important (and time-consuming) part of this.

**Comment by jsfenfen** [comment]
Yeah, +1. Thanks so much for doing this!
